file<- read.table("household_power_consumption.txt", sep=";", na.string="?",header=TRUE)
file[,"Date"]<-as.Date(file[,"Date"],"%d/%m/%Y")
file<-subset(file,Date>=as.Date("2007-02-01") & Date<=as.Date("2007-02-02"))
plot(as.POSIXct(paste(file$Date, data$Time)),file$Sub_metering_1,ylab="Energy sub metering",xlab="", type = "l")
lines(as.POSIXct(paste(file$Date, data$Time)),file$Sub_metering_2, col = "red")
lines(as.POSIXct(paste(file$Date, data$Time)),file$Sub_metering_3, col = "blue")
legend("topright", pch =-1, lty = 1,lwd =2.5, col = c("black", "red", "blue"), legend=c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
dev.copy(png,file="plot3.png",width=480,height=480,units="px")
dev.off()

